bf = read.table('FinalData.csv', sep=',', header=T)
llogit <- glm(SexCode ~ Height+Weight+Class, family = binomial, data = bf)
summary(llogit)
anova(llogit)
anova(llogit, test="Chisq")
full_model <- glm(SexCode ~ Height, family = binomial, data = bf)
reduced_model <- glm(SexCode ~ Weight + Class, family = binomial, data = bf)
anova(reduced_model)
anova(full_model)

linear_model <- lm(Weight~Height+ Sex+ Class, data=bf)
summary(linear_model)
anova(linear_model)
reduced_model1 <- lm(Weight~Sex+Class, data = bf)
anova(reduced_model1)
